title: 'Python for Economists'
author: Rohan Jha
# logo: content/images/econ-models.png
# copyright: '2020'

execute:
  execute_notebooks: off

# repository:
#   url: https://github.com/data-88e/textbook

# launch_buttons:
#     binderhub_url: https://mybinder.org
#     jupyterhub_url: https://datahub.berkeley.edu

html:
  # favicon: content/images/favicon.ico
  # use_repository_button: true
  navbar_number_sections: true

bibtex_bibfiles:
    - references.bib

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
